### ISSUE TITLE
免映射过程中的细节问题

### ISSUE THREAD

**Issue by lovekittynine** [RandyZhouRan/ConNER#1]
作者你好，在paperweekly公众号推文中看到相关的论文介绍。整体上还是能理解的，就是在基于translate-train的一致性训练中使用了免映射的方式，作者提到先将目标词汇标记为span，然后翻译到源语言上，最后将span单独在翻译，得到pair对的词对；这里我的问题是，既然是无标签的目标域数据，怎么确定`目标词汇`呢？对于本身就是短语类的`多元` entity是怎么构造目标词汇？
感谢🙏回复～

**Comment by RandyZhouRan** [comment]
As we explained in the last paragraph of Sec. 2.3 in the original paper (as well as the second paragraph of Sect. 2.2.2.1 in the paperweekly article):

> It is noteworthy that, although our translation-based consistency training is applicable to arbitrary span pairs from the parallel sentences, it would be more valuable for NER task if the selected spans are likely to be entities.
Therefore, we use a weak NER tagger trained with only labeled source-language data to assign NER labels on unlabeled target-language sentences, and use the predicted entities as our candidate spans for consistency training. 
Note that we only use predictions from the weak tagger to locate the boundary of candidate spans, which to some extent reduces the impact of predictions with wrong entity types.

**Comment by lovekittynine** [comment]
ok， 感谢回复～通过在source-language上训练的weak NER tagger是在"translated"后的句子上做实体识别，怎么保证翻译后识别的可能是实体的token和原来的taget sentence中对应的token保持一致的对应关系呢？

**Comment by lovekittynine** [comment]
我的意思是，如果反翻译回去后， 英文的实体token -> french token,  那么这个token很有可能和原本的法语句子中具有相同意思的token不一致吧，这个怎么做映射呢

**Comment by RandyZhouRan** [comment]
As shown in Figure 2 of the paper, we replace the candidate span with a placeholder(e.g., SPAN44), and translate the obtained sentence. It turns out that the translation system (either Google Translate or OPUS-MT) has the capability to preserve the placeholder in the translated sentence, and now the placeholder indicates where the original span is projected to in the translated sentence.
